apiVersion: v1
kind: Namespace
metadata:
  name: af-edge
  labels:
    app.kubernetes.io/part-of: raavan
    af.layer: edge
---
apiVersion: v1
kind: Namespace
metadata:
  name: af-platform
  labels:
    app.kubernetes.io/part-of: raavan
    af.layer: platform
---
apiVersion: v1
kind: Namespace
metadata:
  name: af-runtime
  labels:
    app.kubernetes.io/part-of: raavan
    af.layer: runtime
---
apiVersion: v1
kind: Namespace
metadata:
  name: af-data
  labels:
    app.kubernetes.io/part-of: raavan
    af.layer: data
---
apiVersion: v1
kind: Namespace
metadata:
  name: af-observability
  labels:
    app.kubernetes.io/part-of: raavan
    af.layer: observability
