apiVersion: v1
kind: ConfigMap
metadata:
  name: agent-config
  namespace: agent-framework
data:
  NEXTAUTH_URL: "http://127.0.0.1:3000"
  NEXT_PUBLIC_API_URL: "http://127.0.0.1:8000"
  SPOTIFY_REDIRECT_URI: "http://127.0.0.1:3000/api/spotify/callback"
  GOOGLE_REDIRECT_URI: "http://127.0.0.1:3000/api/auth/google/callback"
  NODE_ENV: "development"
  PORT: "8000"
  CODE_INTERPRETER_URL: ""
  CI_REPLICAS: "1"
  CI_HEADLESS_SERVICE: ""
  CI_NAMESPACE: "agent-framework"
